channels:
  - conda-forge
dependencies:
  # Default Python
  - python=3.9
  - altair
  - matplotlib
  - pandas
  - vega_datasets
  # - pip
  # Default R
  - r-base=4
  - r-essentials
  # JupyterLab
  - jupyterlab=3.0.16
  - jupyterlab-git
  - jupyterlab-python-file
  # R package cinof1: https://github.com/thogaertner/cinof1
  - r-devtools
  - r-bnlearn
  - r-geepack
  - r-psych
  - r-dagitty
  - r-ggplot2
  - r-caret
  - r-doParallel
  - r-v8
  - r-rmarkdown
