channels:
  - conda-forge
dependencies:
  - python=3.9
  - r-base=4
  - r-tidyverse
  - r-devtools
  - r-dagitty
  - r-rmarkdown
  - jupytext
  - jupyterlab-git
  - pip
  - pip:
    - julynter
    - -r file:../requirements.txt