#!/bin/bash

# Install a JupyterLab git extension for pushing changes to git
pip install jupyterlab-git
jupyter labextension install @jupyterlab/git

# Install cinof1
Rscript -e "devtools::install_github('thogaertner/cinof1')"